export const tempoList = [
  "Adagio",
  "Adagietto",
  "Adagissimo",
  "Andante",
  "Andante moderato",
  "Andantino",
  "Allegretto",
  "Allegro",
  "Allegro moderato",
  "Allegro vivace",
  "Allegrissimo",
  "Grave",
  "Larghetto",
  "Larghissimo",
  "Largo",
  "Lento",
  "Marcia moderato",
  "Moderato",
  "Molto allegro",
  "Presto",
  "Prestissimo",
  "Vivace",
  "Vivacissimo",
];

export const tempoMap = {
  Adagio: {
    minBPM: 44,
    maxBPM: 66,
    defaultBPM: 55,
    description: "Slow and melancholic",
  },
  Adagietto: {
    minBPM: 46,
    maxBPM: 88,
    defaultBPM: 67,
    description: "Slower than andante or slightly faster than adagio",
  },
  Adagissimo: {
    minBPM: 24,
    maxBPM: 40,
    defaultBPM: 32,
    description: "Or Grave: Very slow and solemn",
  },
  Andante: {
    minBPM: 56,
    maxBPM: 108,
    defaultBPM: 82,
    description: "At a walking pace, moderately slow",
  },
  "Andante moderato": {
    minBPM: 80,
    maxBPM: 108,
    defaultBPM: 94,
    description:
      "Or Andantino: Between andante and moderato (at a moderate walking speed)",
  },
  Andantino: {
    minBPM: 80,
    maxBPM: 108,
    defaultBPM: 94,
    description:
      "Or Andante moderato: Slightly faster than andante, but slower than moderato (although, in some cases, it can be taken to mean slightly slower than andante)",
  },
  Allegretto: {
    minBPM: 108,
    maxBPM: 120,
    defaultBPM: 114,
    description: "Moderately fast",
  },
  Allegro: {
    minBPM: 120,
    maxBPM: 168,
    defaultBPM: 144,
    description: "Fast and bright",
  },
  "Allegro moderato": {
    minBPM: 116,
    maxBPM: 120,
    defaultBPM: 134,
    description: "Close to, but not quite allegro",
  },
  "Allegro vivace": {
    minBPM: 124,
    maxBPM: 156,
    defaultBPM: 140,
    description:
      "Or Molto allegro: At least slightly faster and livelier than allegro, but always at its range (and no faster than vivace)",
  },
  Allegrissimo: {
    minBPM: 172,
    maxBPM: 176,
    defaultBPM: 174,
    description: "Or Vivacissimo: very fast, lively and bright",
  },
  Grave: {
    minBPM: 24,
    maxBPM: 40,
    defaultBPM: 32,
    description: "Or Adagissimo: Very slow and solemn",
  },
  Larghetto: {
    minBPM: 44,
    maxBPM: 66,
    defaultBPM: 55,
    description: "Rather slow and broad",
  },
  Larghissimo: {
    minBPM: 1,
    maxBPM: 24,
    defaultBPM: 16,
    description: "Extremely slow, slowest type of tempo",
  },
  Largo: {
    minBPM: 40,
    maxBPM: 66,
    defaultBPM: 53,
    description: "Slow and broad",
  },
  Lento: {
    minBPM: 40,
    maxBPM: 60,
    defaultBPM: 50,
    description: "Slow",
  },
  "Marcia moderato": {
    minBPM: 66,
    maxBPM: 80,
    defaultBPM: 73,
    description: "Moderately, in the manner of a march",
  },
  Moderato: {
    minBPM: 108,
    maxBPM: 120,
    defaultBPM: 114,
    description: "At a moderate speed",
  },
  "Molto allegro": {
    minBPM: 124,
    maxBPM: 156,
    defaultBPM: 140,
    description:
      "Or Allegro vivace: At least slightly faster and livelier than allegro, but always at its range (and no faster than presto)",
  },
  Presto: {
    minBPM: 168,
    maxBPM: 200,
    defaultBPM: 184,
    description: "Very fast",
  },
  Prestissimo: {
    minBPM: 200,
    maxBPM: 500,
    defaultBPM: 200,
    description: "Extremely fast",
  },
  Vivace: {
    minBPM: 156,
    maxBPM: 176,
    defaultBPM: 166,
    description: "Fast and lively",
  },
  Vivacissimo: {
    minBPM: 172,
    maxBPM: 176,
    defaultBPM: 174,
    description: "Or Allegrissimo: very fast, lively and bright",
  },
};
